#!/usr/bin/env python3
"""
Compute LCOM4 (Lack of Cohesion in Methods, variant 4) for every class in a
C++ header/source file pair, or scan the entire project for a named class.

LCOM4 graph
-----------
  Nodes  : every method with a user-defined body in the header or source file
           + every instance field accessed by at least one such method
  Edges  : method -> field   (method accesses that field)
           method -> method  (method calls another method of the same class)
  Result : number of connected components
           1 = fully cohesive
           N > 1 = class should be split into N classes

Qt noise excluded automatically
--------------------------------
  - Q_OBJECT-injected methods  (metaObject, qt_metacast, qt_metacall, etc.)
  - QPrivateSignal inner struct (injected by Q_OBJECT)
  - Signals: their bodies are generated by MOC into moc_*.cpp, so they have
    no user-defined definition and are never added as graph nodes.

Include paths / compiler flags
-------------------------------
  --build-dir must point to a CMake build directory with compile_commands.json.
  The flags used by the real build are extracted for each source file, so Qt
  and project headers are resolved exactly as the compiler sees them:

      cmake -B build_claude -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

  Without --build-dir the script falls back to a minimal flag set
  (-std=c++14 plus the header's own directory), which is only sufficient
  for headers with no external dependencies.

Usage
-----
  Analyse a single file pair:
    python tools/lcom4.py Foo.h Foo.cpp --build-dir build_claude
    python tools/lcom4.py Foo.h Foo.cpp --build-dir build_claude --verbose

  Scan the whole project for every file that defines a given class:
    python tools/lcom4.py --class MyClass --build-dir build_claude
    python tools/lcom4.py --class MyClass --build-dir build_claude --verbose

Requirements
------------
    # Option 1: system package (Ubuntu/Debian):
    apt install python3-clang
    # Option 2: pip (bundles libclang, no separate clang install needed):
    pip install libclang
"""

import argparse
import functools
import re
import sys
from collections import defaultdict
from pathlib import Path
from typing import Dict, Generator, List, Optional, Set, Tuple

try:
    import clang.cindex as cindex
except ImportError:
    sys.exit("Error: 'clang' package not found.  "
             "Run: apt install python3-clang  OR  pip install libclang")


# Type aliases for clarity in function signatures.
FilePath   = str  # absolute or relative path to a file on disk
ClassName  = str  # C++ class name (e.g. "FileDownloader")
MemberName = str  # C++ field or method name (e.g. "m_downloadTasks")
NodeId     = str  # LCOM4 graph node identifier: "m:<method>" or "f:<field>"


# ---------------------------------------------------------------------------
# Graph - connected-component counter
# ---------------------------------------------------------------------------

def _build_adjacency(edges: List[Tuple[NodeId, NodeId]]) -> Dict[NodeId, Set[NodeId]]:
    adj: Dict[NodeId, Set[NodeId]] = defaultdict(set)
    for a, b in edges:
        adj[a].add(b)
        adj[b].add(a)
    return adj


def _reachable(start: NodeId, adj: Dict[NodeId, Set[NodeId]], visited: Set[NodeId]) -> Set[NodeId]:
    """Return all nodes reachable from start, updating visited in place (iterative BFS)."""
    component: Set[NodeId] = set()
    queue = [start]
    while queue:
        node = queue.pop()
        if node in visited:
            continue
        visited.add(node)
        component.add(node)
        queue.extend(adj[node])
    return component


def connected_components(
    nodes: Set[NodeId], edges: List[Tuple[NodeId, NodeId]]
) -> Tuple[int, List[Set[NodeId]]]:
    adj = _build_adjacency(edges)
    visited: Set[NodeId] = set()
    components: List[Set[NodeId]] = []
    for node in nodes:
        if node not in visited:
            components.append(_reachable(node, adj, visited))
    return len(components), components


# ---------------------------------------------------------------------------
# libclang helpers
# ---------------------------------------------------------------------------

def _iter_file_nodes(
    tu: cindex.TranslationUnit, allowed_files: Set[FilePath]
) -> Generator[cindex.Cursor, None, None]:
    """Yield cursors from allowed_files only, skipping foreign top-level subtrees entirely.

    Iterating the full TU with walk_preorder() visits every Qt/stdlib declaration
    before the Python file filter can discard it.  By pruning at the TU's direct
    children we never enter those subtrees at all.
    """
    resolve_cache: Dict[str, str] = {}
    for top in tu.cursor.get_children():
        if top.location.file is None:
            continue
        raw = top.location.file.name
        if raw not in resolve_cache:
            resolve_cache[raw] = str(Path(raw).resolve())
        if resolve_cache[raw] not in allowed_files:
            continue
        yield from top.walk_preorder()


def _find_all_classes(
    tu: cindex.TranslationUnit,
    header_file: FilePath,
    class_name: Optional[ClassName] = None,
) -> List[cindex.Cursor]:
    """Return class/struct definition cursors declared in header_file within tu.

    tu is the TU parsed from the .cpp source; the class definitions are found
    there because the .cpp includes the header.  Only nodes whose location
    resolves to header_file are considered, so Qt base classes defined in Qt
    headers are not returned.

    Args:
        tu:          Translation unit parsed from the .cpp source file.
        header_file: Absolute resolved path of the header to search in.
        class_name:  If given, return only the class with this exact name.
    """
    return [
        cursor
        for cursor in _iter_file_nodes(tu, {header_file})
        if cursor.kind in (cindex.CursorKind.CLASS_DECL, cindex.CursorKind.STRUCT_DECL)
        if cursor.is_definition()
        if cursor.spelling != 'QPrivateSignal'
        if class_name is None or cursor.spelling == class_name
    ]


# Methods injected by the Q_OBJECT macro, excluded from the graph.
_QT_OBJECT_METHODS: Set[MemberName] = frozenset({
    'metaObject', 'qt_metacast', 'qt_metacall', 'qt_static_metacall', 'tr', 'trUtf8',
})


def _class_members(class_cursor: cindex.Cursor) -> Tuple[Set[MemberName], Set[MemberName]]:
    """Return (field names, method names) declared directly in the class.

    Methods in _QT_OBJECT_METHODS are excluded; they are injected by Q_OBJECT
    and have no meaningful field access to analyse.
    """
    fields: Set[MemberName] = set()
    methods: Set[MemberName] = set()
    for c in class_cursor.get_children():
        if c.kind == cindex.CursorKind.FIELD_DECL:
            fields.add(c.spelling)
        elif c.kind == cindex.CursorKind.CXX_METHOD and c.spelling not in _QT_OBJECT_METHODS:
            methods.add(c.spelling)
    return fields, methods


def _is_own_member(cursor: cindex.Cursor, class_usr: str, kind: cindex.CursorKind) -> bool:
    """Return True if cursor references a member of class_usr with the given cursor kind."""
    ref = cursor.referenced
    return (ref is not None
            and ref.semantic_parent is not None
            and ref.semantic_parent.get_usr() == class_usr
            and ref.kind == kind)


def _references_own_field(cursor: cindex.Cursor, class_usr: str) -> bool:
    return _is_own_member(cursor, class_usr, cindex.CursorKind.FIELD_DECL)


def _calls_own_method(cursor: cindex.Cursor, class_usr: str) -> bool:
    return _is_own_member(cursor, class_usr, cindex.CursorKind.CXX_METHOD)


def _walk_body(
    cursor: cindex.Cursor, class_usr: str
) -> Tuple[Set[MemberName], Set[MemberName]]:
    """Return (fields accessed, methods called) by this cursor's subtree within class_usr."""
    used_fields: Set[MemberName] = set()
    called_methods: Set[MemberName] = set()
    for node in cursor.walk_preorder():
        if node.kind == cindex.CursorKind.MEMBER_REF_EXPR and _references_own_field(node, class_usr):
            used_fields.add(node.referenced.spelling)
        elif node.kind == cindex.CursorKind.CALL_EXPR and _calls_own_method(node, class_usr):
            called_methods.add(node.referenced.spelling)
    return used_fields, called_methods


def _report_diagnostics(tu: cindex.TranslationUnit, path: FilePath) -> None:
    for d in tu.diagnostics:
        if d.severity >= cindex.Diagnostic.Error:
            print(f"[parse warning] {path}: {d.spelling}", file=sys.stderr)


# ---------------------------------------------------------------------------
# Per-class LCOM4 computation
# ---------------------------------------------------------------------------

def _collect_method_usages(
    tu: cindex.TranslationUnit,
    source_files: Set[FilePath],
    class_usr: str,
) -> Tuple[Set[MemberName], Dict[MemberName, Set[MemberName]], Dict[MemberName, Set[MemberName]]]:
    """Scan method bodies in source_files and return (defined_methods, field_uses, method_calls).

    Only method definitions whose location falls within source_files are analysed,
    which naturally excludes Qt signals (their bodies are in MOC-generated files).
    """
    defined_methods: Set[MemberName] = set()
    field_uses:   Dict[MemberName, Set[MemberName]] = defaultdict(set)
    method_calls: Dict[MemberName, Set[MemberName]] = defaultdict(set)

    for cursor in _iter_file_nodes(tu, source_files):
        if not (cursor.kind == cindex.CursorKind.CXX_METHOD
                and cursor.is_definition()
                and cursor.semantic_parent.get_usr() == class_usr):
            continue
        name = cursor.spelling
        defined_methods.add(name)
        fields, calls = _walk_body(cursor, class_usr)
        field_uses[name].update(fields)
        method_calls[name].update(calls)

    return defined_methods, field_uses, method_calls


def _build_lcom4_graph(
    methods:      Set[MemberName],
    field_uses:   Dict[MemberName, Set[MemberName]],
    method_calls: Dict[MemberName, Set[MemberName]],
) -> Tuple[Set[NodeId], List[Tuple[NodeId, NodeId]]]:
    """Build the LCOM4 graph (nodes, edges) from member usage data."""
    method_nodes: Set[NodeId] = {f'm:{m}' for m in methods}
    field_nodes:  Set[NodeId] = {f'f:{f}' for fs in field_uses.values() for f in fs}

    field_edges = [(f'm:{m}', f'f:{f}') for m, fs in field_uses.items()   for f in fs]
    call_edges  = [
        (f'm:{m}', f'm:{c}')
        for m, cs in method_calls.items()
        for c in cs
        if f'm:{c}' in method_nodes
    ]

    return method_nodes | field_nodes, field_edges + call_edges


def _compute_lcom4_for_class(
    class_cursor: cindex.Cursor,
    tu: cindex.TranslationUnit,
    source_files: Set[FilePath],
) -> dict:
    """Compute LCOM4 for a single class.

    Args:
        class_cursor: Cursor for the class declaration (from the header).
        tu:           Translation unit parsed from the .cpp source file.
        source_files: Absolute resolved paths of the header and .cpp.  Only
                      method definitions found in these files are analysed;
                      this naturally excludes Qt signals, whose bodies are
                      generated by MOC into moc_*.cpp (not in source_files).
    """
    class_usr = class_cursor.get_usr()
    fields, methods_decl = _class_members(class_cursor)

    defined_methods, field_uses, method_calls = _collect_method_usages(tu, source_files, class_usr)
    methods_decl = methods_decl.intersection(defined_methods)  # signals have no body in source_files; drop them

    nodes, edges = _build_lcom4_graph(methods_decl, field_uses, method_calls)
    lcom4, components = connected_components(nodes, edges)

    return {
        'lcom4':      lcom4,
        'class':      class_cursor.spelling,
        'methods':    sorted(methods_decl),
        'fields':     sorted(fields),
        'components': [sorted(c, key=lambda x: (x[0], x[2:])) for c in components],
    }


# ---------------------------------------------------------------------------
# File-level entry points
# ---------------------------------------------------------------------------

def _filter_compiler_args(raw_args: List[str], filepath: FilePath) -> List[str]:
    """Strip build-only flags from a raw compiler command argument list.

    Removes the compiler executable, output flags and their values (-o, -MF, etc.),
    standalone build flags (-c, -MD, etc.), and the input file path itself.
    What remains are the flags meaningful for re-parsing (-std, -I, -D).
    """
    _skip_with_value = {'-o', '-MF', '-MT', '-MQ'}
    _skip_bare       = {'-c', '-MD', '-MMD', '-MP'}
    abs_path = str(Path(filepath).resolve())

    filtered: List[str] = []
    it = iter(raw_args[1:])  # skip compiler executable
    for arg in it:
        if arg in _skip_with_value:
            next(it, None)
        elif arg not in _skip_bare and arg not in (filepath, abs_path):
            filtered.append(arg)
    return filtered


@functools.lru_cache(maxsize=None)
def _load_compdb(build_dir: FilePath) -> Optional[cindex.CompilationDatabase]:
    """Load and cache a CompilationDatabase from build_dir."""
    try:
        return cindex.CompilationDatabase.fromDirectory(build_dir)
    except cindex.CompilationDatabaseError:
        return None


def _args_from_compdb(build_dir: FilePath, filepath: FilePath) -> Optional[List[str]]:
    """Return filtered compiler args from compile_commands.json for filepath, or None."""
    compdb = _load_compdb(build_dir)
    if compdb is None:
        return None
    commands = compdb.getCompileCommands(str(Path(filepath).resolve()))
    if not commands:
        return None
    return _filter_compiler_args(list(commands[0].arguments), filepath)


def compute_lcom4(
    header:     FilePath,
    source:     FilePath,
    class_name: Optional[ClassName] = None,
    build_dir:  Optional[FilePath]  = None,
) -> List[dict]:
    """Parse source and return one LCOM4 result dict per class declared in header.

    Only one parse is performed (the .cpp source file).  Class declarations are
    discovered within that TU because the .cpp includes the header; method
    definitions in both the header (inline) and the .cpp are analysed.

    Args:
        header:     Path to the header file (.h).  Used to locate class
                    declarations inside the parsed TU.
        source:     Path to the source file (.cpp).  This is the file that
                    is actually parsed by libclang.
        class_name: If given, analyse only the class with this exact name.
        build_dir:  CMake build directory containing compile_commands.json.
                    Provides the exact -std/-I/-D flags used by the real build.
                    Without it, only a minimal flag set is used (-std=c++14
                    plus the header's own directory), which will fail on any
                    file that includes Qt or other external headers.
    """
    index = cindex.Index.create()

    args_from_db = _args_from_compdb(build_dir, source) if build_dir else None
    if args_from_db is not None:
        base_args = args_from_db
        header_dir = f'-I{Path(header).parent}'
        if header_dir not in base_args:
            base_args = [header_dir] + base_args
    else:
        if build_dir:
            print(f"[compdb] {source} not found in {build_dir}/compile_commands.json"
                  ", falling back to minimal flags.", file=sys.stderr)
        base_args = ['-std=c++14', f'-I{Path(header).parent}']

    tu = index.parse(source, args=base_args)
    _report_diagnostics(tu, source)

    header_abs = str(Path(header).resolve())
    classes = _find_all_classes(tu, header_abs, class_name)
    if not classes:
        raise ValueError(
            f"No class found in {header}"
            + (f" matching {class_name!r}" if class_name else "")
        )

    source_files = {header_abs, str(Path(source).resolve())}
    return [_compute_lcom4_for_class(cls, tu, source_files) for cls in classes]


def _analyse_command(
    command:    cindex.CompileCommand,
    class_name: ClassName,
    build_dir:  FilePath,
    pattern:    re.Pattern,
) -> Optional[Tuple[FilePath, FilePath, List[dict]]]:
    """Analyse one compdb entry; return (header, source, results) or None if class is absent."""
    source = command.filename
    if not source.endswith('.cpp'):
        return None
    header = str(Path(source).with_suffix('.h'))
    if not Path(header).exists():
        return None
    try:
        text = Path(header).read_text(encoding='utf-8', errors='replace')
    except OSError:
        return None
    if not pattern.search(text):
        return None
    try:
        return (header, source, compute_lcom4(header, source, class_name, build_dir))
    except ValueError:
        return None


def scan_project(
    class_name: ClassName, build_dir: FilePath
) -> List[Tuple[FilePath, FilePath, List[dict]]]:
    """Scan all entries in compile_commands.json for files that define class_name.

    For each .cpp in the compilation database, checks whether the matching .h
    (same directory, same basename) contains a declaration of class_name via a
    fast text scan.  libclang is only invoked for files that pass the text check.

    Args:
        class_name: Exact name of the class to look for.
        build_dir:  CMake build directory containing compile_commands.json.

    Returns:
        List of (header_path, source_path, results) for every file where
        class_name was found and successfully analysed.
    """
    try:
        compdb = cindex.CompilationDatabase.fromDirectory(build_dir)
    except cindex.CompilationDatabaseError:
        raise ValueError(f"Could not load compile_commands.json from {build_dir!r}")

    pattern = re.compile(r'\bclass\s+' + re.escape(class_name) + r'\b')
    return list(filter(None, (
        _analyse_command(cmd, class_name, build_dir, pattern)
        for cmd in compdb.getAllCompileCommands()
    )))


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _print_result(result: dict, verbose: bool) -> None:
    print(f"Class  : {result['class']}")
    print(f"Methods: {len(result['methods'])}")
    print(f"Fields : {len(result['fields'])}")
    print(f"LCOM4  : {result['lcom4']}")

    if result['lcom4'] > 1:
        print(f"  -> Cohesion problem: candidate for splitting into {result['lcom4']} classes.")

    if verbose:
        print("  Connected components:")
        for i, comp in enumerate(result['components'], 1):
            methods = [n[2:] for n in comp if n.startswith('m:')]
            fields  = [n[2:] for n in comp if n.startswith('f:')]
            print(f"    [{i}] methods={methods}")
            if fields:
                print(f"         fields ={fields}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description='Compute LCOM4 cohesion metric for C++ classes.',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument('header', nargs='?', default=None,
                        help='Header file (.h), used to locate class declarations.'
                             ' Required in single-file mode; omit for project-wide scan.')
    parser.add_argument('source', nargs='?', default=None,
                        help='Source file (.cpp), parsed by libclang.'
                             ' Required in single-file mode; omit for project-wide scan.')
    parser.add_argument('--class', dest='class_name', default=None,
                        help='Class name to analyse.  In single-file mode, restricts'
                             ' analysis to this class.  Required for project-wide scan.')
    parser.add_argument('--build-dir', default=None, metavar='DIR',
                        help='CMake build directory containing compile_commands.json.'
                             ' Provides exact compiler flags (-std, -I, -D) for each'
                             ' source file.  Required for project-wide scan.  In'
                             ' single-file mode, falls back to minimal flags when absent.')
    parser.add_argument('--verbose', action='store_true',
                        help='Show methods and fields in each connected component.')
    args = parser.parse_args()

    single_file_mode = args.header is not None and args.source is not None
    scan_mode        = args.header is None      and args.source is None

    if not single_file_mode and not scan_mode:
        parser.error('Provide both header and source for single-file mode, '
                     'or neither for project-wide scan.')

    if scan_mode:
        if not args.class_name:
            parser.error('--class is required for project-wide scan.')
        if not args.build_dir:
            parser.error('--build-dir is required for project-wide scan.')
        try:
            matches = scan_project(args.class_name, args.build_dir)
        except ValueError as exc:
            sys.exit(f"Error: {exc}")
        if not matches:
            sys.exit(f"No file found defining class {args.class_name!r}.")
        flat = [(source, result) for _header, source, results in matches for result in results]
        for i, (source, result) in enumerate(flat):
            if i > 0:
                print()
            print(f"File   : {source}")
            _print_result(result, args.verbose)
    else:
        try:
            results = compute_lcom4(args.header, args.source, args.class_name, args.build_dir)
        except ValueError as exc:
            sys.exit(f"Error: {exc}")
        for i, result in enumerate(results):
            if i > 0:
                print()
            _print_result(result, args.verbose)


if __name__ == '__main__':
    main()
