#ifndef COMMONEXPANSE_GLOBAL_H
#define COMMONEXPANSE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COMMONEXPANSE_LIBRARY)
#  define COMMONEXPANSE_EXPORT Q_DECL_EXPORT
#else
#  define COMMONEXPANSE_EXPORT Q_DECL_IMPORT
#endif

#endif // COMMONEXPANSE_GLOBAL_H
